version: "3.8"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=${EMBY_UID:-1000} # The UID to run emby as
      - GID=${EMBY_GID:-100} # The GID to run emby as
      - GIDLIST=${EMBY_GIDLIST:-100} # Additional GIDs
      - TZ=${TZ:-Asia/Taipei} # Timezone
      - EMBY_DEVICE_NAME=${EMBY_DEVICE_NAME:-EmbyServer} # Device name
      - EMBY_SERVER_NAME=${EMBY_SERVER_NAME:-EmbyServer} # Server name
      - EMBY_PUBLISHED_SERVER_URL=${EMBY_PUBLISHED_SERVER_URL} # Published server URL
    volumes:
      - ${EMBY_CONFIG_DIR:-./config}:/config # Configuration directory
      - ${EMBY_MEDIA_DIR:-./media}:/media # Media directory
    ports:
      - ${EMBY_HTTP_PORT:-8096}:8096 # HTTP port
      - ${EMBY_HTTPS_PORT:-8920}:8920 # HTTPS port
    networks:
      - media_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${EMBY_CPU_LIMIT:-2}
          memory: ${EMBY_MEMORY_LIMIT:-4G}
        reservations:
          cpus: ${EMBY_CPU_RESERVATION:-1}
          memory: ${EMBY_MEMORY_RESERVATION:-2G}

networks:
  media_network:
    external: true
