version: "3.9"
services:
  metube:
    container_name: MeTube
    image: ghcr.io/alexta69/metube
    healthcheck:
     test: curl -f http://localhost:8081/ || exit 1
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 5992:8081
    volumes:
      - /mnt/mark15000A/docker/metube/download-acer:/downloads:rw
      - /mnt/mark15000A/docker/metube/cookies:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
